import type { Metadata } from "next";

import "./globals.css";
import Header from "./component/header";
import Footer from "./component/footer";


export const metadata: Metadata = {
  title: "anonChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
